# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    docker:    
      - image: cimg/node:15.1
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run unit tests
          command: npm run test:unit
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Publishes to npm (only for pull requests into master)
  npm-publish:
    working_directory: .
    docker:    
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      # NPM_TOKEN is defined as CircleCI environment variable
      - run:      
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish
      - store_artifacts:
          path: ./dist
  
workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - npm-publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
